# Generated by Django 6.0.6 on 2026-07-07 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nit', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='El NIT debe contener solo dígitos, con un dígito de verificación opcional (ej. 900123456-7).', regex='^\\d{5,15}(-\\d)?$')], verbose_name='NIT')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="El teléfono debe contener entre 7 y 15 dígitos, con un '+' opcional al inicio.", regex='^\\+?\\d{7,15}$')])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
            },
        ),
    ]
